<a href="https://colab.research.google.com/github/halloda/Mushroom_Classification/blob/main/Mushroom_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas
from sklearn import svm
from sklearn.model_selection import train_test_split
from scipy.io import arff
from sklearn.preprocessing import MinMaxScaler 

In [2]:
from google.colab import files
data=files.upload()


Saving mushrooms.csv to mushrooms.csv


In [17]:
full_dataset=pandas.read_csv('mushrooms.csv')
full_dataset.replace([np.inf, -np.inf], np.nan)
full_dataset.fillna(0)

target=full_dataset['class'].copy()
full_dataset.drop('class', axis=1, inplace=True)

enc_df=pandas.get_dummies(full_dataset)
enc_df.fillna(0)

target[target=='p']=1
target[target=='e']=0

Xtrain, Xtest,Ytrain,Ytest=train_test_split(enc_df, target, test_size=.2,random_state=42)

Xtrain=np.asarray(Xtrain)
Ytrain=np.asarray(Ytrain)
Xtest=np.asarray(Xtest)
Ytest=np.asarray(Ytest)

Xtrain=Xtrain.astype(int)
Ytrain=Ytrain.astype(int)
Xtest=Xtest.astype(int)
Ytest=Ytest.astype(int)

print(Xtrain)
print(Xtest)
print(Ytrain)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 1 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]]
[1 1 1 ... 0 1 0]


In [18]:
#Tensorflow NN

import tensorflow as tf
from tensorflow import keras



nnmodel=keras.Sequential([
  keras.layers.Flatten(),
  keras.layers.Dense(35, activation=tf.nn.relu),
  keras.layers.Dense(35, activation=tf.nn.relu),
  keras.layers.Dense(1,activation=tf.nn.sigmoid),
])

nnmodel.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy',tf.keras.metrics.Precision(),tf.keras.metrics.FalsePositives(),tf.keras.metrics.FalseNegatives(),tf.keras.metrics.TrueNegatives(),tf.keras.metrics.TruePositives()])

nnmodel.fit(Xtrain,Ytrain, epochs=1, batch_size=1)

test_loss, test_acc, nnprec,nnfp, nnfn, nntn, nntp =nnmodel.evaluate(Xtest,Ytest)

51/51 [==============================] - 1s 1ms/step - loss: 1.3242e-04 - accuracy: 1.0000 - precision_4: 1.0000 - false_positives_4: 0.0000e+00 - false_negatives_4: 0.0000e+00 - true_negatives_4: 843.0000 - true_positives_4: 782.0000


In [19]:
from sklearn.ensemble import RandomForestClassifier as RFC
from sklearn import metrics

forest=RFC(n_estimators=50)
forest.fit(Xtrain, Ytrain)


newprediction=forest.predict(Xtest)

currForestTest=Ytest

print("Accuracy: ", metrics.accuracy_score(currForestTest,newprediction))

print("Precision: ", metrics.precision_score(currForestTest,newprediction))
TP=0
FP=0
FN=0
TN=0

for i in range(len(newprediction)):
  if currForestTest[i]==newprediction[i]:
    TP+=1
  if newprediction[i]==1 and  currForestTest[i]!=newprediction[i]:
    FP+=1
  if newprediction[i]==0 and currForestTest[i]!=newprediction[i]:
    FN+=1
  if currForestTest[i]==0 and newprediction[i]==0:
    TN+=1

print ("TP: ", TP, " TN: ", TN)
print ("FP ", FP, " FN ", FN)

Accuracy:  1.0
Precision:  1.0
TP:  1625  TN:  843
FP  0  FN  0
